name: Build Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build (optional)'
        required: false
        default: ''

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  get_changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      changed_images: ${{ steps.get_changes.outputs.changed_images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed images
        id: get_changes
        run: |
          changed="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile' | cut -d/ -f1 | sort -u)"
          changed="${changed} ${{ github.event.inputs.image }}"
          echo "changed_images=$(jq -R -s -c '[splits("\\s+")] | map(select(. != ""))' <<< "$changed")" >> $GITHUB_OUTPUT

  build:
    name: Build and push
    runs-on: ubuntu-latest
    needs: get_changes
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        image: ${{fromJson(needs.get_changes.outputs.changed_images)}}
    if: needs.get_changes.outputs.changed_images != '[]'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hardened Images
        uses: docker/login-action@v4
        with:
          registry: dhi.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: cloud
          endpoint: "abihf/github-abihf-images"

      - name: Build and push image (latest, sha)
        id: build
        uses: docker/build-push-action@v7
        with:
          context: ./${{ matrix.image }}
          push: true
          sbom: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
          platforms: linux/amd64
          outputs: type=registry,oci-mediatypes=true,compression=zstd,force-compression=false

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
