name: qBittorrent

on:
  push:
    branches:
      - main
    paths:
      - 'qbittorrent/**'
      - .github/workflows/qbittorrent.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}/qbittorrent

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push (latest + sha)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (latest, sha)
        uses: docker/build-push-action@v4
        
        with:
          context: ./qbittorrent
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
          platforms: linux/amd64